### ISSUE TITLE
not so sure about psr-2 compliance

### ISSUE THREAD

**Issue by ppetermann** [bertptrs/phpstreams#1]
As the psr-2 compliance is especially mentioned in the readme:

Namespaces are part of a fully qualified class name, so i'd assume that namespaces should be StudlyCaps, opposed to all lowercase in this project.

**Comment by bertptrs** [comment]
Hi Peter,

PSR-1 (and by extension PSR-2) explicitly states that class names should be studly caps, but nothing is specified about the namespace names, which is why there are many conforming libraries (e.g. Guzzle) choose to have lowercase namespaces.

The reason I chose to have it this way is because I liken them to `import` statements in Java and those are generally lower case. Otherwise, there is no real reason to have them either way for me.

**Comment by ppetermann** [comment]
Guzzle uses "GuzzleHttp" as namespace, thats not lowercase: see example here:  https://github.com/guzzle/guzzle/blob/master/src/Client.php, and i stick with my "fully qualified name includes namespace" reasoning.

also java conventions are different anyways.

**Comment by bertptrs** [comment]
It appears you're right, I must've remembered wrongly (or confused some libraries, it happens). Anyway, the fully qualified name thing is not specified, and changing it would break compatibility (which is unfortunate at least) with no real benefit.

I am closing this issue. If there is a good reason to change, I am willing to reopen and apply the change.
